# Generated by Django 2.2.4 on 2021-02-15 08:24

from django.db import migrations
from phonenumbers import parse, is_possible_number, is_valid_number, format_number, PhoneNumberFormat


def fill_owner_pure_phone(apps, shema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phone_number = parse(flat.owners_phonenumber, 'RU')
        flat.owner_pure_phone = None
        if is_possible_number(parsed_phone_number) and is_valid_number(parsed_phone_number):
            flat.owner_pure_phone = format_number(parsed_phone_number, PhoneNumberFormat.E164)
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone)
    ]
