# Generated by Django 2.2.4 on 2021-02-15 10:38

from django.db import migrations


def add_owner_flats(apps, shema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                                     owner_pure_phone=flat.owner_pure_phone)
        owner.own_flats.set([flat])


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_auto_20210215_1140'),
    ]

    operations = [
        migrations.RunPython(add_owner_flats)
    ]
